name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Log step 1
      run: echo "Step 1 - Checkout complete"
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Log step 2
      run: echo "Step 2 - Node.js setup complete"

    - run: npm ci
    
    - name: Log step 3
      run: echo "Step 3 - npm ci complete"

#     - run: npm run lint
    
    - name: Log step 4
      run: echo "Step 4 - Linting complete"
